//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 12:28:24 AM CDT 
//


package com.pokesoap.wsdl.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pokesoap.wsdl.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pokesoap.wsdl.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HeldItems }
     * 
     */
    public HeldItems createHeldItems() {
        return new HeldItems();
    }

    /**
     * Create an instance of {@link HeldItems.VersionDetails }
     * 
     */
    public HeldItems.VersionDetails createHeldItemsVersionDetails() {
        return new HeldItems.VersionDetails();
    }

    /**
     * Create an instance of {@link Abilities }
     * 
     */
    public Abilities createAbilities() {
        return new Abilities();
    }

    /**
     * Create an instance of {@link GetAbilitiesRequest }
     * 
     */
    public GetAbilitiesRequest createGetAbilitiesRequest() {
        return new GetAbilitiesRequest();
    }

    /**
     * Create an instance of {@link GetAbilitiesResponse }
     * 
     */
    public GetAbilitiesResponse createGetAbilitiesResponse() {
        return new GetAbilitiesResponse();
    }

    /**
     * Create an instance of {@link GetHeldItemsRequest }
     * 
     */
    public GetHeldItemsRequest createGetHeldItemsRequest() {
        return new GetHeldItemsRequest();
    }

    /**
     * Create an instance of {@link GetHeldItemsResponse }
     * 
     */
    public GetHeldItemsResponse createGetHeldItemsResponse() {
        return new GetHeldItemsResponse();
    }

    /**
     * Create an instance of {@link GetBaseExperienceRequest }
     * 
     */
    public GetBaseExperienceRequest createGetBaseExperienceRequest() {
        return new GetBaseExperienceRequest();
    }

    /**
     * Create an instance of {@link GetBaseExperienceResponse }
     * 
     */
    public GetBaseExperienceResponse createGetBaseExperienceResponse() {
        return new GetBaseExperienceResponse();
    }

    /**
     * Create an instance of {@link GetIdRequest }
     * 
     */
    public GetIdRequest createGetIdRequest() {
        return new GetIdRequest();
    }

    /**
     * Create an instance of {@link GetIdResponse }
     * 
     */
    public GetIdResponse createGetIdResponse() {
        return new GetIdResponse();
    }

    /**
     * Create an instance of {@link GetNameRequest }
     * 
     */
    public GetNameRequest createGetNameRequest() {
        return new GetNameRequest();
    }

    /**
     * Create an instance of {@link GetNameResponse }
     * 
     */
    public GetNameResponse createGetNameResponse() {
        return new GetNameResponse();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncountersRequest }
     * 
     */
    public GetLocationAreaEncountersRequest createGetLocationAreaEncountersRequest() {
        return new GetLocationAreaEncountersRequest();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncountersResponse }
     * 
     */
    public GetLocationAreaEncountersResponse createGetLocationAreaEncountersResponse() {
        return new GetLocationAreaEncountersResponse();
    }

    /**
     * Create an instance of {@link HeldItems.Item }
     * 
     */
    public HeldItems.Item createHeldItemsItem() {
        return new HeldItems.Item();
    }

    /**
     * Create an instance of {@link HeldItems.VersionDetails.Version }
     * 
     */
    public HeldItems.VersionDetails.Version createHeldItemsVersionDetailsVersion() {
        return new HeldItems.VersionDetails.Version();
    }

    /**
     * Create an instance of {@link Abilities.Ability }
     * 
     */
    public Abilities.Ability createAbilitiesAbility() {
        return new Abilities.Ability();
    }

}
